
select
    FL_DATE,
    OP_UNIQUE_CARRIER,
    OP_CARRIER_FL_NUM,
    ORIGIN,
    DEST,
    DEP_TIME,
    DEP_DELAY,
    TAXI_OUT,
    WHEELS_OFF,
    WHEELS_ON,
    TAXI_IN,
    ARR_TIME,
    ARR_DELAY,
    -- Colonnes manquantes dans la table 2019 : on renvoie NULL
    null as CRS_DEP_TIME,
    null as CRS_ARR_TIME,
    null as CANCELLED,
    null as CANCELLATION_CODE,
    null as DIVERTED,
    null as CRS_ELAPSED_TIME,
    null as ACTUAL_ELAPSED_TIME,
    AIR_TIME,
    DISTANCE,
    CARRIER_DELAY,
    WEATHER_DELAY,
    NAS_DELAY,
    SECURITY_DELAY,
    LATE_AIRCRAFT_DELAY
from {{ source('raw_flight_data', '2019') }}
