# .streamlit/secrets.toml

[gcp_service_account]
type = "service_account"
project_id = "flightops-analytics"
private_key_id = "17d41ebe32ce5dddeb6383081dcd622e40554ded"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDrw+mJ0unJf7XG
o+nOJ226hwpa0tEsRgONSrs2DbAA6TWos0EDQ2CM1eADkn6wFB4FXfWWif1n4r2R
6UwIu+5y2Dt2vnKmiOLFgFMIYzNYWH8ErWA1+HkBE56CCqK0ipAvaRrOtiYKZnLh
MTdWh7giitH7WwUOcE7eaphk2yoQl/T+VUyg18fwi+u7Z2n8yLsmU4Y+sx9FiaEg
QjyzC4VtQLgwy10Y3KX05y69Gg68Erh57dYP8V21OnJgqhZwnlIZ355QNqvN/MwS
ylnBCs6xoBCMO64+7N2OB/vmiu2FlkfSSLOkdVxIeAAM/BDSrMC99/TzfrJcoxRz
P9d97knDAgMBAAECggEAEy7vLzAyppsWGtIWgZgytPUs8gPqUixmOJZmkjjd480V
+SKQvSe70OnMHu5KEaCpaq1hAL08mbnYy+kMLz+/YKfYesp3QLatoP1WhD2yHVOi
DirfQ7Tyf5Rtls4vu/n0Tm9CZ6RphvocCde71XYYlPLvsACRckHQIQfSW457pzrW
D5T44RzLhpeOB3o+/m3KytIfoH+JtBlKiLzScKfB7JFUypax+9i9n1vyQkLfWKUW
zZIyyCHoqn0zii1JzJa9jsEp6iVni4wjm0OXcKwbl3iWTKedTr74yl0uGmivBLKK
GJJQZuFEvvwG5LGlaoXJC/p28njknYmGDGpTmoBEkQKBgQD549uJGZqKd+I8nSqO
gPe9Li43sC6wtFpdNOf1+UmVWui/s9NuPbWNyviRMYmDPJuUScvYhv2HsjiDbj1I
v+aZ94ip1NJu/EtI8CQHTFGKsUSCxPPrr/RJxuMKIaFdfxX76BSJ5CMtj1PRSmDR
wLfkepWl/YtfsHyZ8CRmyb4oEwKBgQDxh6Si5zKl2FaBV2bE74x5iQMtEM0/5bO8
Uh6eUP7nS2+xcN8JpGnTiEN2h3QksGNdYZq8fjCNF9+I3Wfujq2tvaIgawFz9UIU
VrROdWrhdlPV7A7lnFPiwhS4Lg8bow0ENdgJuI9EGTD1YW/2WsxWt7rKMvOheul0
+F8bHWDtkQKBgEDW48buMtBNDRHnQfyZ8C5RRkLC30qQcYYPzURgu7waS5w6X9kS
AALbsKWT8fdwiXnvsAnt9Oj50Hoh55rx2DcJKJfQlg2gPzScwux13A6dsoYv7o6w
KDXgelbNpR4qdJzZekLRRGN09i2vG/IxDEYnnJ7ma/yXQa17xyY4oLOrAoGAUcZ4
MoOOvWIC3+XksLbeW+PMxHxU0daGxTMUlMudklgTKAOsMEqPXgRbuwzfgPCLo/lA
96LN82dq0p8L6lQ6b4GuG8W/BzC5v8MfZxUQK+fxOJOk8467RCIr+7P0f4n0BUHp
tFjdgNP6pInp64IQfyfTwVQA8uJ3mpfhM3/96lECgYBZrx6ZA3TSHOYqta1YkNuZ
8Z3+TUz68Y2OL+xFAQpvfySwdDe9AuQZrElhGrN/pbnpDlZlJ29zdzEStyH/y3a2
A0R/wSNTBz1/2+9YTXaMyypW4IKP+nxrVVpAKnm/YDBD47rNHv7/+hGV8mLkjg/Q
FXM5OCaBPt/AE8V0UzAzoA==
-----END PRIVATE KEY-----"""
client_email = "dbt-user-247@flightops-analytics.iam.gserviceaccount.com"
client_id = "111400964110353507204"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/dbt-user-247%40flightops-analytics.iam.gserviceaccount.com"
universe_domain = "googleapis.com"